In [43]:
from sklearn import datasets
import numpy as np
data = datasets.load_breast_cancer()

In [44]:
print(data.feature_names.shape)
print(data.feature_names)

(30,)
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [45]:
data.target.shape

(569,)

In [46]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [47]:
data.data.shape

(569, 30)

In [48]:
data.data[0:5, 0:4]

array([[  17.99,   10.38,  122.8 , 1001.  ],
       [  20.57,   17.77,  132.9 , 1326.  ],
       [  19.69,   21.25,  130.  , 1203.  ],
       [  11.42,   20.38,   77.58,  386.1 ],
       [  20.29,   14.34,  135.1 , 1297.  ]])

In [49]:
from keras.utils import to_categorical
one_hot_targets = to_categorical(data.target)

In [50]:
data.target[0:5]

array([0, 0, 0, 0, 0])

In [51]:
one_hot_targets.shape

(569, 2)

In [52]:
one_hot_targets[0:5]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [53]:
col_means = data.data.mean(axis=0)
col_stds = data.data.std(axis=0)

In [54]:
np.mean(data.data)

61.890712339519624

In [55]:
np.std(data.data)

228.29740508276657

In [56]:
norm_data = data.data - col_means
norm_data = norm_data/col_stds

In [57]:
np.mean(norm_data)

-6.118909323768877e-16

In [58]:
np.std(norm_data)

1.0

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(norm_data, data.target, 
                                                     shuffle=True, random_state=42,
                                                    test_size=.2)
print("{} {}: {} {}".format(X_train.shape, X_test.shape, y_train.shape, y_test.shape))

(455, 30) (114, 30): (455,) (114,)


In [60]:
from keras import models
from keras import layers

def build_model(shape):
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu', input_shape=shape))
    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer='rmsprop', loss='mse', metrics=['acc'])
    return model

In [61]:
model = build_model(shape=(data.data.shape[1],))

In [62]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 64)                1984      
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 65        
Total params: 2,049
Trainable params: 2,049
Non-trainable params: 0
_________________________________________________________________


In [63]:
history = model.fit(X_train, y_train, batch_size=30, verbose=1, validation_split=0.2, epochs=20)


Train on 364 samples, validate on 91 samples
Epoch 1/20
364/364 [==============================] - 0s 422us/step - loss: 0.1438 - acc: 0.8159 - val_loss: 0.0944 - val_acc: 0.9231
Epoch 2/20
364/364 [==============================] - 0s 57us/step - loss: 0.0720 - acc: 0.9451 - val_loss: 0.0663 - val_acc: 0.9121
Epoch 3/20
364/364 [==============================] - 0s 60us/step - loss: 0.0519 - acc: 0.9643 - val_loss: 0.0550 - val_acc: 0.9341
Epoch 4/20
364/364 [==============================] - 0s 51us/step - loss: 0.0418 - acc: 0.9670 - val_loss: 0.0473 - val_acc: 0.9451
Epoch 5/20
364/364 [==============================] - 0s 53us/step - loss: 0.0348 - acc: 0.9670 - val_loss: 0.0434 - val_acc: 0.9451
Epoch 6/20
364/364 [==============================] - 0s 52us/step - loss: 0.0300 - acc: 0.9780 - val_loss: 0.0403 - val_acc: 0.9451
Epoch 7/20
364/364 [==============================] - 0s 69us/step - loss: 0.0261 - acc: 0.9808 - val_loss: 0.0373 - val_acc: 0.9560
Epoch 8/20
364/364 [===